### ISSUE TITLE
[Testnet 0.12] Error: getaddrinfo ENOENT when waking from sleep mode

### ISSUE THREAD

**Issue by SebastienGllmt** [input-output-hk/daedalus#1212]
On Testnet Daedalus 0.12.0 (Windows 10)
If my computer goes to sleep mode after syncing the blockchain, waking up the computer gets me stuck on `Starting Cardano Node...`

Here is the error log from `Daedalus.log`

```
[2018-12-06T05:39:46.0533Z] [debug] [renderer] Local blockchain height: 306574
[2018-12-06T05:39:46.0533Z] [debug] [renderer] Network blockchain height: 306575
[2018-12-06T05:39:46.0533Z] [debug] [renderer] Total unsynced blocks at node start: 77
[2018-12-06T05:39:46.0533Z] [debug] [renderer] Blocks synced since node start: 76
[2018-12-06T06:28:04.0029Z] [debug] [renderer] System time change detected
[2018-12-06T06:28:04.0031Z] [debug] [renderer] AdaApi::getNetworkStatus (FORCE-NTP-CHECK) called
[2018-12-06T06:28:04.0032Z] [debug] [renderer] AdaApi::getNetworkStatus called
[2018-12-06T06:28:04.0395Z] [debug] [renderer] AdaApi::nextUpdate called
[2018-12-06T06:28:04.0395Z] [debug] [renderer] AdaApi::getWallets called
[2018-12-06T06:28:04.0396Z] [error] [renderer] AdaApi::getNetworkStatus (FORCE-NTP-CHECK) error: {
  "stack": "Error: getaddrinfo ENOENT localhost:29827\n    at Object.exports._errnoException (util.js:1050:11)\n    at errnoException (dns.js:33:15)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)",
  "message": "getaddrinfo ENOENT localhost:29827",
  "code": "ENOENT",
  "errno": "ENOENT",
  "syscall": "getaddrinfo",
  "hostname": "localhost",
  "host": "localhost",
  "port": 29827
}
```

Restarting Daedalus fixes the issue.

**Comment by nikolaglumac** [comment]
Thanks for the report @SebastienGllmt.
May I ask you if you see the same problem with the current production/mainnet Daedalus?

**Comment by SebastienGllmt** [comment]
Oh hey you're right -- I get the same error on current mainnet Daedalus. However, it seems that the mainnet Daedalus auto-recovers after a few minutes. Testnet Daedalus seems to be stuck indefinitely.

Here is the error on Mainnet Daedalus (from which I recover after a few minutes of `connecting to network...`)
```
renderer.js:34 [19:06:41.402] AdaApi::nextUpdate error: {
  "stack": "Error: getaddrinfo ENOENT localhost:8090\n    at Object.exports._errnoException (util.js:1050:11)\n    at errnoException (dns.js:33:15)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)",
  "message": "getaddrinfo ENOENT localhost:8090",
  "code": "ENOENT",
  "errno": "ENOENT",
  "syscall": "getaddrinfo",
  "hostname": "localhost",
  "host": "localhost",
  "port": 8090
}
```

**Comment by cleverca22** [comment]
it also matters heavily how long the computer has been in sleep mode, if its only been a few minutes, it can recover

but if its been in sleep mode for an hour, the connection may fail, and then it takes longer to recover

**Comment by nikolaglumac** [comment]
The issue has been resolved in: https://github.com/input-output-hk/daedalus/pull/1213
