### ISSUE TITLE
Error when running development procedures or installation with Nix

### ISSUE THREAD

**Issue by mzabani** [input-output-hk/daedalus#2452]
Hi! I cloned the repository and tried to follow the instructions to run Daedalus with Nix, but was unable to. I'm on NixOS, edited nix.conf accordingly and then ran instructions (long post because all the output is also pasted below). It is my first time running _any_ Cardano wallet, and am going the development route because I didn't find daedalus in nixpkgs, so sorry if this is some lame mistake of mine! Thanks for all the great work too.

Errors when installing (happens on `master`, `develop` and `release/3.3.2`):
````bash
$ nix build -f ./release.nix mainnet.installer
error: attribute 'installer' in selection path 'mainnet.installer' not found
````

The development path:
````bash
$ git checkout release/3.3.2 # master also runs into the same problems
$ nix-shell
trace: Using IOHK default nixpkgs
trace: Version 1 is deprecated: use version 2 (nixpkgs arguments are available as the `nixpkgsArgs` attribute of version 2)
trace: gitSource.nix: /nix/store/lp3n3y8gz43ixzz5cn5zks0m5sz5z99n-cardano-shell-src does not seem to be a git repository,
assuming it is a clean checkout.
trace: WARNING: license "GPL-2.0-or-later AND BSD-3-Clause" not found
trace: Using index-state: 2020-05-15T00:00:00Z for cardano-shell
trace: Using IOHK default nixpkgs
trace: gitSource.nix: /nix/store/li372796j2x7zygy3q8i87dybm1l6kxc-cardano-node-src does not seem to be a git repository,
assuming it is a clean checkout.
trace: To make project.plan-nix for cardano-node-src a fixed-output derivation but not materialized, set `plan-sha256` to the output of the 'calculateMaterializedSha' script in 'passthru'.
trace: To materialize project.plan-nix for cardano-node-src entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
trace: To make project.plan-nix for cardano-node-src a fixed-output derivation but not materialized, set `plan-sha256` to the output of the 'calculateMaterializedSha' script in 'passthru'.
trace: To materialize project.plan-nix for cardano-node-src entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
ln: missing file operand
Try 'ln --help' for more information.
ln: missing file operand
Try 'ln --help' for more information.
ln: missing file operand
Try 'ln --help' for more information.
ln: failed to create symbolic link 'Release/usb_bindings.node': File exists
ln: failed to create symbolic link 'Release/HID.node': File exists
yarn install v1.22.10
[1/4] Resolving packages...
warning Resolution field "unicode-properties@1.1.0" is incompatible with requested version "unicode-properties@^1.2.2"
success Already up-to-date.
$ yarn build:electron
yarn run v1.22.10
$ electron-rebuild -f -w usb
✔ Rebuild Complete
Done in 13.70s.
Done in 15.47s.
ln: failed to create symbolic link './node_modules/electron/dist/electron': No such file or directory
'./node_modules/electron-chromedriver/bin/chromedriver' -> '/nix/store/6f3nz903rsic7vfmq4qr6f0p3921v1dh-chromedriver-87.0.4280.88/bin/chromedriver'
jq < $LAUNCHER_CONFIG
debug the node by running debug-node

$  yarn nix:mainnet
yarn run v1.22.10
$ NETWORK=mainnet nix-shell --argstr nodeImplementation cardano --argstr cluster mainnet
trace: Using IOHK default nixpkgs
trace: Version 1 is deprecated: use version 2 (nixpkgs arguments are available as the `nixpkgsArgs` attribute of version 2)
trace: gitSource.nix: /nix/store/lp3n3y8gz43ixzz5cn5zks0m5sz5z99n-cardano-shell-src does not seem to be a git repository,
assuming it is a clean checkout.
trace: WARNING: license "GPL-2.0-or-later AND BSD-3-Clause" not found
trace: Using index-state: 2020-05-15T00:00:00Z for cardano-shell
trace: Using IOHK default nixpkgs
trace: gitSource.nix: /nix/store/li372796j2x7zygy3q8i87dybm1l6kxc-cardano-node-src does not seem to be a git repository,
assuming it is a clean checkout.
trace: To make project.plan-nix for cardano-node-src a fixed-output derivation but not materialized, set `plan-sha256` to the output of the 'calculateMaterializedSha' script in 'passthru'.
trace: To materialize project.plan-nix for cardano-node-src entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
trace: To make project.plan-nix for cardano-node-src a fixed-output derivation but not materialized, set `plan-sha256` to the output of the 'calculateMaterializedSha' script in 'passthru'.
trace: To materialize project.plan-nix for cardano-node-src entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
ln: missing file operand
Try 'ln --help' for more information.
ln: missing file operand
Try 'ln --help' for more information.
ln: missing file operand
Try 'ln --help' for more information.
ln: failed to create symbolic link 'Release/usb_bindings.node': File exists
ln: failed to create symbolic link 'Release/HID.node': File exists
[1/4] Resolving packages...
warning Resolution field "unicode-properties@1.1.0" is incompatible with requested version "unicode-properties@^1.2.2"
success Already up-to-date.
$ yarn build:electron
$ electron-rebuild -f -w usb
✔ Rebuild Complete
ln: failed to create symbolic link './node_modules/electron/dist/electron': No such file or directory
'./node_modules/electron-chromedriver/bin/chromedriver' -> '/nix/store/6f3nz903rsic7vfmq4qr6f0p3921v1dh-chromedriver-87.0.4280.88/bin/chromedriver'
jq < $LAUNCHER_CONFIG
debug the node by running debug-node

$ yarn dev
$ IS_WATCH_MODE=true gulp dev
[14:52:24] Using gulpfile ~/Projects/daedalus/gulpfile.js
[14:52:24] Starting 'dev'...
[14:52:24] Starting 'server:create:dev'...
[14:52:24] Finished 'server:create:dev' after 7.15 ms
[14:52:24] Starting 'build:watch'...
[14:52:24] Starting 'clean:dist'...
[14:52:24] Finished 'clean:dist' after 99 ms
[14:52:24] Starting 'server:create:dev'...
[14:52:24] Finished 'server:create:dev' after 5.75 ms
[14:52:24] Starting 'build:renderer:html'...
[14:52:24] Finished 'build:renderer:html' after 31 ms
[14:52:24] Starting 'build:main:watch'...
[14:52:33] Finished 'build:main:watch' after 8.83 s
[14:52:33] Starting 'build:renderer:watch'...
[14:52:33] webpack is watching for changes
[14:52:56] Finished 'build:renderer:watch' after 23 s
[14:52:56] Finished 'build:watch' after 32 s
[14:52:56] Starting 'server:start'...
[14:52:56] webpack is watching for changes
[14:52:56] Finished 'server:start' after 86 ms
[14:52:56] Finished 'dev' after 32 s
internal/validators.js:120
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at normalizeSpawnArguments (child_process.js:411:3)
    at Object.spawn (child_process.js:547:16)
    at spawn (/home/mzabani/Projects/daedalus/node_modules/electron-connect/node_modules/cross-spawn/index.js:17:18)
    at ProcessManager.spawn (/home/mzabani/Projects/daedalus/node_modules/electron-connect/lib/server.js:56:23)
    at ProcessManager.<anonymous> (/home/mzabani/Projects/daedalus/node_modules/electron-connect/lib/server.js:79:10)
    at Object.onceWrapper (events.js:420:28)
    at Server.emit (events.js:326:22)
    at Server.EventEmitter.emit (domain.js:506:15)
    at emitListeningNT (net.js:1350:10)
    at processTicksAndRejections (internal/process/task_queues.js:83:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````

**Comment by nikolaglumac** [comment]
I suggest you to try the steps for running Daedalus described in https://github.com/input-output-hk/daedalus#running-daedalus-with-cardano-node

e.g. for Mainnet:

Run yarn nix:mainnet from daedalus.
Run yarn dev from the subsequent nix-shell

**Comment by nikolaglumac** [comment]
Sorry, I've missed the second part of your post.
Not sure what that error is - we are all running dev mode on macOS.
Perhaps @disassembler or @cleverca22 can help us out here?

**Comment by danielmain** [comment]
Hi @mzabani I made a video how can I run Daedalus from a NixOS environment. (That is, in fact, my machine where I code for Daedalus).

https://drive.google.com/file/d/1XII8le_fTytCGGMbHBxSpNAmjL4j-qET/view?usp=sharing

Please reopen if you can still reproduce it and provide me more info about which branch and which NixOS are you using. Thanks!
