### ISSUE TITLE
glibc error in nix shell

### ISSUE THREAD

**Issue by locallycompact** [input-output-hk/daedalus#2752]
Hi, running

```
yarn nix:mainnet
yarn dev
```

results in 

```
App threw an error during load
Error: /nix/store/vbr3p4y2azrgwq2s7h2hbip8x06w50z5-glibc-2.32-24/lib/libc.so.6: version `GLIBC_2.33' not found (required by /home/lc/Source/github.com/input-output-hk/daedalus/node_modules/usb/build/Debug/usb_bindings.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (/home/lc/Source/github.com/input-output-hk/daedalus/dist/main/index.js:28782:48)
    at Object../node_modules/usb/usb.js (/home/lc/Source/github.com/input-output-hk/daedalus/dist/main/index.js:211076:112)
(node:794769) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `electron --trace-deprecation ...` to show where the warning was created)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /nix/store/vbr3p4y2azrgwq2s7h2hbip8x06w50z5-glibc-2.32-24/lib/libc.so.6: version `GLIBC_2.33' not found (required by /home/lc/Source/github.com/input-output-hk/daedalus/node_modules/usb/build/Debug/usb_bindings.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (/home/lc/Source/github.com/input-output-hk/daedalus/dist/main/index.js:28782:48)
    at Object../node_modules/usb/usb.js (/home/lc/Source/github.com/input-output-hk/daedalus/dist/main/index.js:211076:112)
/nix/store/vbr3p4y2azrgwq2s7h2hbip8x06w50z5-glibc-2.32-24/lib/libc.so.6: version `GLIBC_2.33' not found (required by /nix/store/ji67dqqh5dw4v7v0plfshvi2hiilr7yp-gvfs-1.48.1/lib/gio/modules/libgvfsdbus.so)
```

in current master

**Comment by nikolaglumac** [comment]
Hi @locallycompact! Can you please check the latest master (it has been updated today) or try out the develop branch?

**Comment by locallycompact** [comment]
Still the same

**Comment by nikolaglumac** [comment]
Can you please share more info about your system/environment?

**Comment by locallycompact** [comment]
Never mind, I had a dirty working tree. It launches now. Thank you!
