### ISSUE TITLE
Error: Render frame was disposed before WebFrameMain could be accessed

### ISSUE THREAD

**Issue by morucci** [input-output-hk/daedalus#2874]
Hi,
I'm using 4.8.0 version and from time to time daedalus does not start and fails with the following error:
```
Error: Render frame was disposed before WebFrameMain could be accessed
    at Object._send (<anonymous>)
    at Object.n.send (electron/js2c/browser_init.js:165:413)
    at Object.b.send (electron/js2c/browser_init.js:161:2494)
    at /nix/store/vcki2a117r83c0rp6y4mpfv2x1dqlws3-daedalus-js/share/daedalus/main/index.js:84169:21
    at Array.forEach (<anonymous>)
    at transport (/nix/store/vcki2a117r83c0rp6y4mpfv2x1dqlws3-daedalus-js/share/daedalus/main/index.js:84168:33)
    at log (/nix/store/vcki2a117r83c0rp6y4mpfv2x1dqlws3-daedalus-js/share/daedalus/main/index.js:83615:15)
    at Object.error (/nix/store/vcki2a117r83c0rp6y4mpfv2x1dqlws3-daedalus-js/share/daedalus/main/index.js:226049:79)
    at handleError (/nix/store/vcki2a117r83c0rp6y4mpfv2x1dqlws3-daedalus-js/share/daedalus/main/index.js:226089:53)
    at process.<anonymous> (/nix/store/vcki2a117r83c0rp6y4mpfv2x1dqlws3-daedalus-js/share/daedalus/main/index.js:226096:5)
[launcher:Notice:7] [2022-02-11 12:05:30.88 UTC] Wallet exited with exitcode: ExitFailure 7
[launcher:Notice:7] [2022-02-11 12:05:30.88 UTC] Daedalus exited with ExitFailure 7, will shutdown cardano-launcher
```

**Comment by CarlosLopezDeLara** [comment]
@danielmain This was also seen here: https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1644339575876219?thread_ts=1644332036.328279&cid=GGKFXSKC6

**Comment by danielmain** [comment]
@morucci would you please share more info about your hardware and operating systems and help us to reproduce it? 
Thank you!!

**Comment by morucci** [comment]
Hi, sure I'm running on a Lenovo T440s 8Gb RAM + 16GB swap on Fedora 34. CPU i7-4600U

**Comment by morucci** [comment]
I no longer see it with the last version. I close here and re-open if needed.
Thanks !
