### ISSUE TITLE
Errors from wallet code

### ISSUE THREAD

**Issue by erikd** [input-output-hk/daedalus#635]
I build cardano/daedalus using by own build script available here : https://github.com/erikd/cardano-linux-pkg

When run, daedalus starts syncing with the network, but also reports numerous errors like the following to stdout:
```
[20:10:31:0033] [error] AdaApi::syncProgress error: {
  "stack": "Error: connect ECONNREFUSED 127.0.0.1:8090\n    at Object.exports._errnoException (util.js:1050:11)\n    at exports._exceptionWithHostPort (util.js:1073:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)",
  "message": "connect ECONNREFUSED 127.0.0.1:8090",
  "code": "ECONNREFUSED",
  "errno": "ECONNREFUSED",
  "syscall": "connect",
  "address": "127.0.0.1",
  "port": 8090
}
```
The Mac version of daedalus installed from the official installer doesn't report anything like this.

Its my understanding that `127.0.0.1:8090` is `cardano-node` but I don't understand why it is both reporting these errors *and* syncing at the same time.

**Comment by dantrevino** [comment]
I'm seeing the same thing, with my own locally built version.
![image](https://user-images.githubusercontent.com/7738/34476305-7ba29ba6-ef44-11e7-94f2-2fae9923c083.png)
```
[1] [22:38:19:0752] [error] AdaApi::syncProgress error: {
[1]   "stack": "Error: connect ECONNREFUSED 127.0.0.1:8090\n    at Object.exports._errnoException (util.js:1050:11)\n    at exports._exceptionWithHostPort (util.js:1073:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)",
[1]   "message": "connect ECONNREFUSED 127.0.0.1:8090",
[1]   "code": "ECONNREFUSED",
[1]   "errno": "ECONNREFUSED",
[1]   "syscall": "connect",
[1]   "address": "127.0.0.1",
[1]   "port": 8090
[1] }
[1] [22:38:19:0761] [error] AdaApi::getLocalTimeDifference error: {
[1]   "stack": "Error: connect ECONNREFUSED 127.0.0.1:8090\n    at Object.exports._errnoException (util.js:1050:11)\n    at exports._exceptionWithHostPort (util.js:1073:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)",
[1]   "message": "connect ECONNREFUSED 127.0.0.1:8090",
[1]   "code": "ECONNREFUSED",
[1]   "errno": "ECONNREFUSED",
[1]   "syscall": "connect",
[1]   "address": "127.0.0.1",
[1]   "port": 8090
[1] }
```

**Comment by dantrevino** [comment]
My bad. This appears to be a dup of #608
