### ISSUE TITLE
npm run test failed with blank screen window

### ISSUE THREAD

**Issue by inferrna** [input-output-hk/daedalus#659]
It seems like no backend running on expected address
http://storage9.static.itmages.com/i/18/0111/h_1515676009_6409555_0739522c03.png
```
~/dev/daedalus$ npm --verbose run test
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', '--verbose', 'run', 'test' ]
npm info using npm@3.10.10
npm info using node@v6.12.3
npm verb run-script [ 'pretest', 'test', 'posttest' ]
npm info lifecycle daedalus@0.8.0~pretest: daedalus@0.8.0
npm info lifecycle daedalus@0.8.0~test: daedalus@0.8.0

> daedalus@0.8.0 test /home/inferno/dev/daedalus
> npm run cucumber

npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'cucumber' ]
npm info using npm@3.10.10
npm info using node@v6.12.3
npm verb run-script [ 'precucumber', 'cucumber', 'postcucumber' ]
npm info lifecycle daedalus@0.8.0~precucumber: daedalus@0.8.0
npm info lifecycle daedalus@0.8.0~cucumber: daedalus@0.8.0

> daedalus@0.8.0 cucumber /home/inferno/dev/daedalus
> cross-env NODE_ENV=test BABEL_DISABLE_CACHE=1 cucumber-js --compiler js:babel-register --format 'progress-bar' --format-options '{"snippetInterface": "synchronous"}' --tags 'not @skip'

1) Scenario: User accepts "Terms of use" # features/accept-terms-of-use.feature:7
   ✔ Before # features/support/electron.js:41
   ✔ Before # features/support/i18n.js:4
   ✔ Before # features/support/webdriver.js:4
   ✔ Given I didnt accept "Terms of use" # features/step_definitions/accept-terms-of-use-steps.js:11
   ✖ And I have selected English language # features/step_definitions/select-language-steps.js:7
       Error: element (".LanguageSelectionForm_component") still not visible after 20000ms
           at new WaitUntilTimeoutError (/home/inferno/dev/daedalus/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:150:12)
           at /home/inferno/dev/daedalus/node_modules/webdriverio/build/lib/commands/waitUntil.js:29:19
   - Given I am on the "Terms of use" screen # features/step_definitions/accept-terms-of-use-steps.js:17
   - And I click on "I agree with terms of use" checkbox # features/step_definitions/accept-terms-of-use-steps.js:21
   - When I submit the "Terms of use" form # features/step_definitions/accept-terms-of-use-steps.js:25
   - Then I should not see the "Terms of use" screen anymore # features/step_definitions/accept-terms-of-use-steps.js:29
   - And I should have "Terms of use" accepted # features/step_definitions/accept-terms-of-use-steps.js:33
```

**Comment by DanielRrr** [comment]
Similar trouble

**Comment by nikolaglumac** [comment]
You must run your own local Cardano demo cluster: https://github.com/input-output-hk/daedalus/blob/master/README.md#connect-to-local-demo-cluster in order for the Daedalus tests to work.
