### ISSUE TITLE
SyncProcess Error

### ISSUE THREAD

**Issue by mesudip** [input-output-hk/daedalus#713]
The daedalus wallet is trying to connct to 8090 port. Am i supposed to run anything else before `npm run dev` ?
```
[1] [22:52:47:0554] [error] AdaApi::syncProgress error: {
[1]   "stack": "Error: connect ECONNREFUSED 127.0.0.1:8090\n    at Object.exports._errnoException (util.js:1050:11)\n    at exports._exceptionWithHostPort (util.js:1073:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)",
[1]   "message": "connect ECONNREFUSED 127.0.0.1:8090",
[1]   "code": "ECONNREFUSED",
[1]   "errno": "ECONNREFUSED",
[1]   "syscall": "connect",
[1]   "address": "127.0.0.1",
[1]   "port": 8090
[1] }
[1] [22:52:47:0573] [error] AdaApi::getLocalTimeDifference error: {
[1]   "stack": "Error: connect ECONNREFUSED 127.0.0.1:8090\n    at Object.exports._errnoException (util.js:1050:11)\n    at exports._exceptionWithHostPort (util.js:1073:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)",
[1]   "message": "connect ECONNREFUSED 127.0.0.1:8090",
[1]   "code": "ECONNREFUSED",
[1]   "errno": "ECONNREFUSED",
[1]   "syscall": "connect",
[1]   "address": "127.0.0.1",
[1]   "port": 8090
[1] }

```

**Comment by zmeel** [comment]
I guess you need to run cardamom-sl too.

**Comment by zmeel** [comment]
you need to run the cardano-sl node too.

**Comment by mesudip** [comment]
Thanks, that's what I was missing
is it the same case if i download binaries from the daedalus website?

**Comment by zmeel** [comment]
Yes, same case. Daedalus is the wallet en cardano-sl is the node. You need both.
