### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by khwerhahn** [input-output-hk/daedalus#770]
Hi,

cloned the repo and `npm install`. The error output:

```
npm WARN daedalus@0.8.0 No repository field.
npm WARN daedalus@0.8.0 No license field.
npm ERR! Darwin 17.4.0
npm ERR! argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
```
What seems to be the problem here?

**Comment by cleverca22** [comment]
which version of nodejs are you using?

**Comment by khwerhahn** [comment]
node: v9.7.1
npm: 5.6.0

**Comment by cleverca22** [comment]
try using nodejs 6 instead, thats what is currently used

**Comment by khwerhahn** [comment]
Thanks for the answer, but same error occurs. 

```
npm ERR! Linux 4.9.60-linuxkit-aufs
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
npm ERR! node v6.13.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! daedalus@0.8.0 start: `cross-env NODE_ENV=production electron ./`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the daedalus@0.8.0 start script 'cross-env NODE_ENV=production electron ./'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the daedalus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production electron ./
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs daedalus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls daedalus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/daedalus/daedalus/npm-debug.log
```
This happens in my Dockerbuild:
```

FROM ubuntu:16.04

# Install basic requirements and create cardano user
RUN apt-get update
RUN apt-get install -y bzip2 curl git libasound2 libgconf-2-4 \
                                         libgtk2.0.0 libnotify-bin libnss3 libxss1
RUN apt-get install -y xfce4 xfce4-goodies tightvncserver
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash
RUN apt-get install -y nodejs build-essential libssl-dev
RUN apt-get install -y --no-install-recommends apt-utils
RUN apt-get clean && rm -fr /var/lib/apt/lists/*
RUN useradd -ms /bin/bash daedalus


WORKDIR /home/daedalus
USER daedalus
RUN git clone https://github.com/input-output-hk/daedalus.git
WORKDIR /home/daedalus/daedalus
RUN npm install
RUN npm build
RUN npm run start
```

**Comment by cleverca22** [comment]
i think its trying to actually run electron to start the wallet

**Comment by khwerhahn** [comment]
I get the container to build, but not to run.

```
FROM ubuntu:16.04

RUN apt-get update
RUN apt-get install -y build-essential libssl-dev \
                bzip2 curl git libasound2 libgconf-2-4 \
                libgtk2.0.0 libnotify-bin libnss3 libxss1 \
                xfce4 xfce4-goodies tightvncserver
RUN apt-get install -y --no-install-recommends apt-utils
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash
RUN apt-get install -y nodejs
RUN apt-get clean && rm -fr /var/lib/apt/lists/*
RUN useradd -ms /bin/bash daedalus

WORKDIR /home/daedalus
USER daedalus
RUN npm i -D electron@latest
RUN git clone https://github.com/input-output-hk/daedalus.git
WORKDIR /home/daedalus/daedalus
RUN mkdir -p node_modules/daedalus-client-api
RUN npm install && npm run package
RUN cp installers/ca.conf installers/client.conf installers/server.conf .
RUN bash installers/build-certificates-unix.sh
RUN rm -f tls/server.key && ln -s tls/server/server.key tls/server.key
RUN rm -f tls/server.cert && ln -s tls/server/server.crt tls/server.cert
RUN rm ca.conf client.conf server.conf

CMD npm start
```
Here is the log file for building it: https://www.dropbox.com/s/a1w9rwfrq9uz0im/my-image.build.log?dl=0

When I run the container it exits with:

```
daedalus@0.8.0 start /home/daedalus/daedalus
> cross-env NODE_ENV=production electron ./


npm ERR! Linux 4.9.60-linuxkit-aufs
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.13.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! daedalus@0.8.0 start: `cross-env NODE_ENV=production electron ./`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the daedalus@0.8.0 start script 'cross-env NODE_ENV=production electron ./'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the daedalus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production electron ./
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs daedalus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls daedalus
```

**Comment by cleverca22** [comment]
thats a problem i ran into with electron, it just silently exits if it cant connect to Xorg, try something simple like xterm and youll see that gui programs arent working, you need to fix that first

**Comment by khwerhahn** [comment]
Could you reccomend a good article on how to get this working?

**Comment by dogpatchmedia** [comment]
This took me forever to figure out. Heres the solution I found: use node 6 not node 7.

// install nvm
curl https://raw.githubusercontent.com/creationix/nvm/v0.25.0/install.sh | bash

// get node 6
nvm install v6

// use node 6
nvm use v6

source: https://github.com/h4ck3rm1k3/daedalus/blob/master/README.md

**Comment by datlife** [comment]
I confirm the solution above work for `npm install`

**Comment by ajensenwaud** [comment]
I had the same error using Node v9. The above solution works, however, it would be good to see support for more contemporary Node / NPM versions.

**Comment by javierjmc** [comment]
Well it's not working for me. Here's the log:
```
$ npm install

> daedalus@0.10.0 postinstall /home/javier/github/cardano-sl/daedalus
> node node_modules/fbjs-scripts/node/check-dev-engines.js package.json


assert.js:84
  throw new assert.AssertionError({
  ^
AssertionError: Current node version is not supported for development, expected "6.14.2" to satisfy "8.x".
    at Object.<anonymous> (/home/javier/github/cardano-sl/daedalus/node_modules/fbjs-scripts/node/check-dev-engines.js:39:3)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
    at bootstrap_node.js:507:3

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/babel-cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none was installed.
npm WARN daedalus@0.10.0 No repository field.
npm WARN daedalus@0.10.0 No license field.
npm ERR! Linux 4.15.0-22-generic
npm ERR! argv "/home/javier/.nvm/versions/node/v6.14.2/bin/node" "/home/javier/.nvm/versions/node/v6.14.2/bin/npm" "install"
npm ERR! node v6.14.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! daedalus@0.10.0 postinstall: `node node_modules/fbjs-scripts/node/check-dev-engines.js package.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the daedalus@0.10.0 postinstall script 'node node_modules/fbjs-scripts/node/check-dev-engines.js package.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the daedalus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/fbjs-scripts/node/check-dev-engines.js package.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs daedalus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls daedalus
npm ERR! There is likely additional logging output above.

```

**Comment by nikolaglumac** [comment]
Daedalus now uses nix setup which means you no longer need to run `npm install` manually: https://github.com/input-output-hk/daedalus#start-daedalus-using-demo-cluster
