### ISSUE TITLE
Stuck Connecting to Network After Incomplete Sync

### ISSUE THREAD

**Issue by reidblomquist** [input-output-hk/daedalus#785]
Steps to reproduce:

1. Be running last release
2. Stop sync part way through
3. Not open wallet for a bit; update hits
4. Install update to try to be able to connect; no dice (still spins forever)

I have resolved this by following the steps to fix syncing stuck issues (delete contents of DB-1.0 (I think, still syncing).

Wish this wallet was more stable and releases didn't break things - are there any open bug bounties or tasks lists internally around issues listed in the FAQ? Could help contribute if given some direction.

**Comment by greggdourgarian** [comment]
Hey Reid...couldn't follow your steps...in #1 "running the latest release" and in #4 "install update".  What update did you install if running the latest release?

**Comment by assal01** [comment]
Hey @greggdourgarian  I think I follow @reidblomquist  points, if you read #3 it will be clear. 
Reid stayed some time away from his wallet, when he decided to open it again, network error, then Reid noticed there was an update to the wallet, so he did the update in an attempt to get the issue fixed.
I understand because it is EXACTLY my case as well, and I am stuck exactly at the same point.

**Comment by reidblomquist** [comment]
Yeah, sorry @greggdourgarian #1 is clearer if it reads run old release or previous release (not last)

**Comment by reidblomquist** [comment]
I'm actually stuck connecting to network again today after successfully syncing all blocks fresh after updating

**Comment by domenkozar** [comment]
Did you send a bug report via Daedalus?

**Comment by reidblomquist** [comment]
No, I just saw that this last time but it started syncing and now it's stuck at syncing blocks 99.64%. This is starting to drive me crazy, and I *really* don't want to re-sync the entire chain for the 2nd time in two days. What pertinent logs can I provide you?

**Comment by greggdourgarian** [comment]
hey Reid...you've tried the usual: reboot, check firewall...

**Comment by reidblomquist** [comment]
Yep, rebooted more than once; firewall is fine. Not seeing any errors in the /pub/Daedalus.log other than an issue connecting to :8090 and then it seems fine and just loops the following: 

```
[2018-03-11 20:31:33:0174] [info] Using certificates from: C:\Program Files\Daedalus\tls\ca\ca.crt
[2018-03-11 20:31:36:0511] [debug] AdaApi::syncProgress called
[2018-03-11 20:31:36:0532] [debug] AdaApi::syncProgress called
[2018-03-11 20:31:37:0216] [debug] Stopped polling local time difference
[2018-03-11 20:31:37:0228] [debug] Stopped polling local time difference
[2018-03-11 20:31:38:0333] [error] AdaApi::syncProgress error: {
  "stack": "Error: connect ECONNREFUSED 127.0.0.1:8090\n    at Object.exports._errnoException (util.js:1050:11)\n    at exports._exceptionWithHostPort (util.js:1073:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)",
  "message": "connect ECONNREFUSED 127.0.0.1:8090",
  "code": "ECONNREFUSED",
  "errno": "ECONNREFUSED",
  "syscall": "connect",
  "address": "127.0.0.1",
  "port": 8090
}
[2018-03-11 20:31:38:0356] [debug] Connection Lost. Reconnecting...
[2018-03-11 20:31:38:0356] [debug] Connection Lost. Reconnecting...
[2018-03-11 20:31:38:0356] [debug] Connection Lost. Reconnecting...
[2018-03-11 20:31:38:0511] [debug] AdaApi::syncProgress called
[2018-03-11 20:31:39:0051] [debug] AdaApi::syncProgress success: {
  "_spLocalCD": {
    "getChainDifficulty": {
      "getBlockCount": 727383
    }
  },
  "_spNetworkCD": null,
  "_spPeers": 0
}
[2018-03-11 20:31:39:0053] [info] ========== Connected after 2554 milliseconds ==========
[2018-03-11 20:31:39:0053] [debug] Initial difficulty: {"localDifficulty":727383,"networkDifficulty":null}
[2018-03-11 20:31:39:0053] [debug] Local difficulty changed: 727383
[2018-03-11 20:31:39:0053] [debug] Started polling local time difference
[2018-03-11 20:31:39:0054] [debug] AdaApi::getLocalTimeDifference called
[2018-03-11 20:31:39:0056] [debug] Network difficulty changed: null
[2018-03-11 20:31:39:0178] [debug] AdaApi::syncProgress called
[2018-03-11 20:31:39:0203] [debug] AdaApi::getLocalTimeDifference success: 0
[2018-03-11 20:31:39:0616] [debug] Stopped polling local time difference
[2018-03-11 20:31:39:0781] [debug] AdaApi::syncProgress success: {
....
```

```
}
[2018-03-11 20:32:43:0216] [debug] Local difficulty changed: 727383
[2018-03-11 20:32:43:0216] [debug] Network difficulty changed: 731038
[2018-03-11 20:32:44:0510] [debug] AdaApi::syncProgress called
[2018-03-11 20:32:44:0545] [debug] AdaApi::syncProgress success: {
  "_spLocalCD": {
    "getChainDifficulty": {
      "getBlockCount": 727383
    }
  },
  "_spNetworkCD": {
    "getChainDifficulty": {
      "getBlockCount": 731038
    }
  },
  "_spPeers": 0
}
[2018-03-11 20:32:44:0547] [debug] Local difficulty changed: 727383
[2018-03-11 20:32:44:0547] [debug] Network difficulty changed: 731038
[2018-03-11 20:32:45:0179] [debug] AdaApi::syncProgress called
[2018-03-11 20:32:45:0214] [debug] AdaApi::syncProgress success: {
  "_spLocalCD": {
    "getChainDifficulty": {
      "getBlockCount": 727383
    }
  },
  "_spNetworkCD": {
    "getChainDifficulty": {
      "getBlockCount": 731038
    }
  },
  "_spPeers": 0
}
[2018-03-11 20:32:45:0215] [debug] Local difficulty changed: 727383
[2018-03-11 20:32:45:0215] [debug] Network difficulty changed: 731038
[2018-03-11 20:32:46:0512] [debug] AdaApi::syncProgress called
[2018-03-11 20:32:46:0541] [debug] AdaApi::syncProgress success: {
  "_spLocalCD": {
    "getChainDifficulty": {
      "getBlockCount": 727383
    }
  },
  "_spNetworkCD": {
    "getChainDifficulty": {
      "getBlockCount": 731038
    }
  },
  "_spPeers": 0
}
[2018-03-11 20:32:46:0543] [debug] Local difficulty changed: 727383
[2018-03-11 20:32:46:0543] [debug] Network difficulty changed: 731038
```

**Comment by greggdourgarian** [comment]
Try a different port?  Also, what are your ping times looking like?

**Comment by reidblomquist** [comment]
Try a different port? Lol, what? Are you referring to 127.0.0.1:8090, cuz... you can't ping ports?

**Comment by greggdourgarian** [comment]
hi Reid...try pinging say www.google.com...what kind of latency do u see?   Reason is i saw code or a comment in Daedalus to the effect of rejecting connections if it's too slow.   Plz check and make sure no other app is using port 8090.

**Comment by reidblomquist** [comment]
@greggdourgarian believe me, I've tried the regular troubleshooting things - I opened this ticket with the intent of getting help from project maintainers or team members, or perhaps pitch in with a PR myself. Your comments are kind of just adding noise to the issue.

**Comment by greggdourgarian** [comment]
Let's see that PR hotshot!

**Comment by reidblomquist** [comment]
@domenkozar I'm going to close this so Gregg no longer has a forum to toot his own horn. I will attempt to dig into it on my own a bit and accept that I may have to completely re-sync the chain yet again and that you and your team are hard at work improving Daedalus. Hoping I can use my current app data/state to delve into the issue further with a dev build.
