### ISSUE TITLE
`ENOTFOUND` @ dns.js

### ISSUE THREAD

**Issue by vantuz-subhuman** [input-output-hk/daedalus#960]
Node is running ok, Daedalus is stuck on "Connecting to network...". Daedalus log shows this:
```
[2018-06-04T12:43:32.0930Z] [debug] Connection Lost. Reconnecting...
[2018-06-04T12:43:33.0178Z] [debug] AdaApi::syncProgress called
[2018-06-04T12:43:33.0180Z] [error] AdaApi::syncProgress error: {
  "stack": "Error: getaddrinfo ENOTFOUND localhost localhost:8090\n    at errnoException (dns.js:28:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)",
  "message": "getaddrinfo ENOTFOUND localhost localhost:8090",
  "code": "ENOTFOUND",
  "errno": "ENOTFOUND",
  "syscall": "getaddrinfo",
  "hostname": "localhost",
  "host": "localhost",
  "port": 8090
}
```

OSX High Sierra - 10.13.4 (17E202) on a new Macbook Pro.

**Comment by vantuz-subhuman** [comment]
Suggestion came up to propose user to check his local DNS-settings with this manual: http://osxdaily.com/2014/04/12/restore-original-hosts-file-mac/

Gonna send it to the user and report later.

**Comment by vantuz-subhuman** [comment]
Turned out the user had **empty** `/etc/hosts` file on his Macbook Pro. As soon as he replaced it with the normal "hosts" - everything works perfectly. Example of the valid "hosts" file can be found here: http://osxdaily.com/2014/04/12/restore-original-hosts-file-mac/
